### ISSUE TITLE
IOS app still 'Loading.....' after update OctoPrint to 1.3.10

### ISSUE THREAD

**Issue by AMFkuna** [MoonshineSG/OctoPrint-Mobile#74] opened 2018-12-17 14:29 UTC
I'm sorry, I have overlooked the same problem below.

**Comment by AMFkuna** [comment] 2018-12-17 14:31
Hi, after update to OctoPrint 1.3.10 I cannot connect to my printers with IOS app.
Via mobile Safari OK.

**Comment by keithellis74** [comment] 2018-12-22 19:01
I’m having this problem too, the App just hangs on the loading screen.

**Comment by MoonshineSG** [comment] 2018-12-22 20:02
Sorry guys, on holiday... early jan i’ll have a look and fix it...

**Comment by MoonshineSG** [comment] 2018-12-26 21:53
There have been some changes in the way Octoprint handles authentication keys and that is the most probable cause for the issue. 
Unfortunately I am away without access to a proper computer (only tablet and smart phone) so I am not able to debug. 
Most likely, beginning of Jan i’ll Come out with a solution... Holiday season and all...

**Comment by MoonshineSG** [comment] 2019-01-02 02:56
1.3.10 has introduced "application keys". until i managed to support that feature make sure API key support is still enabled

**Comment by bigsubgit** [comment] 2019-01-02 04:04
Many thanks, I’ll trying asap and I’ll give you a feedback. 
Regards.

**Comment by keithellis74** [comment] 2019-01-02 07:31
API key is still enabled on my system.  I still get notifications to my mobile device but the App does not get beyond the loading screen.

**Comment by MoonshineSG** [comment] 2019-01-02 08:41
notifications work independently ....

do you have a user setup ?

**Comment by keithellis74** [comment] 2019-01-02 09:12
> do you have a user setup ?

Yes I do.  I've just noticed that you can add an API key to a user, rather than just use the API key in the settings page.  However, this also does not appear to work.

**Comment by MoonshineSG** [comment] 2019-01-06 02:48
I can’t replicate this. Can a few of you describe your system ? Versions, network config, etc.... Trying to find a common thing that could point to the cause...

**Comment by AMFkuna** [comment] 2019-01-06 07:31
Hi I have Orange PI+2 with  ARMBIAN 5.65 stable Ubuntu 18.04.1 LTS 4.14.78-sunxi connectet via wifi
With Octoprint 1.3.9 all working fine, but after online update from Octoprint to version 1.3.10
Nautilus app stop working.

**Comment by MoonshineSG** [comment] 2019-01-07 04:34
other plugins running ?

**Comment by klaus-schuster** [comment] 2019-01-07 16:02
I have rasp. 3b+ with the octoprint sd card image from the webside (1 weeks old) 
"2018-04-18-octopi-stretch-lite-0.15.1.img" + after first startup update to version 1.3.10
Plugins:
Action Command Prompt (comes with the image)
CuraEngine (<= 15.04) (comes with the image)
Telegram
Nautilus :-)

Printer: anycubic i3 mega

**Comment by MoonshineSG** [comment] 2019-01-08 04:43
> > I can’t replicate this. Can a few of you describe your system ? Versions, network config, etc.... Trying to find a common thing that could point to the cause...
> 
> I'm running
> 
> ```
> OctoPrint version : 1.3.10
> OctoPi version    : 0.15.1
> ```
> Nautalus was working great until I did the upgrade to OctoPrint 1.13.10 via the web interface
> 
> pip version
> 
> ```
> (oprint) pi@octopi:~/oprint/bin $ pip --version
> pip 9.0.3 from /home/pi/oprint/local/lib/python2.7/site-packages (python 2.7)
> ```
> I've can't remember if I upgraded this pip or if it was an instance at the Makerspace I did.
> 
> ## Plugins
> * Action Command Prompt Support
> * Announcement Plugin
> * Anoymous Usage Tracking
> * Application Keys Plugin
> * Backup and Restore
> * Core Wizard
> * CureaEngine - **disabled**
> * Discovery
> * EEPROM Repetier Editor Plugin (0.1.2)
> * FloatingNavbar (0.3.0)
> * Force Login
> * Logging
> * M84 Motors Off (0.1.0)
> * Nautilus (1.22)
> * Navbar Temperature Plugin (0.11)
> * Pi Support Plugin
> * Plugin Manager
> * Printer Safety Check
> * Software Update
> * Virtual Printer
> * Webcam Tab (0.1.2)
> 
> ## Networking
> Using ethernet socket into a wireless mesh satalite hub.
> 
> Do you need any more info?
> Regards,
> Keith.

all the plugins where there before .10 update ? can you check the logs for any error messages ? (even if not from Nautilus)

**Comment by bigsubgit** [comment] 2019-01-08 09:42
By the way, is the app already able to use application keys?
I just seen that I haven’t any keys in my installation yet, and I don’t understand how I could create a key. 
A.

**Comment by klaus-schuster** [comment] 2019-01-08 11:49
> By the way, is the app already able to use application keys? I just seen that I haven’t any keys in my installation yet, and I don’t understand how I could create a key. A.

you'll find them in your **user** settings.

**Comment by MoonshineSG** [comment] 2019-01-08 12:09
No, application keys not (yet?) supported. The current API key is not going anywhere for a while so app keys will not be implemented in the near future... 

But I still need to figure out why you guys have issues... Can’t replicate the behaviour, and that makes it difficult, if not impossible to figure out what’s wrong...

**Comment by keithellis74** [comment] 2019-01-08 21:01
> all the plugins where there before .10 update ? can you check the logs for any error messages ? (even if not from Nautilus)

Yes all the plugins were there before the update.
I've downloaded the last two Octoprint Logs, I can't find any for Nautalus
[octoprint.log.txt](https://github.com/MoonshineSG/OctoPrint-Mobile/files/2738425/octoprint.log.txt)
[octoprint.log.2019-01-07.2019-01-07.txt](https://github.com/MoonshineSG/OctoPrint-Mobile/files/2738426/octoprint.log.2019-01-07.2019-01-07.txt)

Regards,
Keith.

**Comment by PRGeno** [comment] 2019-01-09 14:14
Same issue here with OctoPrint 1.3.10 and IOS 12.1.2 on My iPhone XS Max and 12.1.1 on my iPad Pro.  Everything had been working fine for a long time until the last 2 OctoPrint updates.  OctoPrint API support is enabled, the Nautilus plugin is installed and up to date, the correct API key and IP address is configured in Nautilus on the IOS App side. Nothing but the "Loading" screen shows up on the app side until it times out.  I have attached my current OctoPrint log to possibly help you troubleshoot.  The IP address ending in x.x.x.128 is the iPhone X running the Nautilus app.
 
[Octoprint Log.txt](https://github.com/MoonshineSG/OctoPrint-Mobile/files/2741189/Octoprint.Log.txt)

**Comment by MoonshineSG** [comment] 2019-01-09 14:51
thanks. that might help. tried to “shake” the phone or go back to printed list  (swipe right from edge), “fake edit” - edit but save without modifying  - maybe does some good - it should do a full reload of the web app  ...

**Comment by MoonshineSG** [comment] 2019-01-09 14:55
also, try to disable “force login” plugin, see if it makes a difference...

**Comment by PRGeno** [comment] 2019-01-09 15:19
Shaking & fake edit of settings did not help.  I don't see any option to disable "force login" anywhere in OctoPrint.  Where might I find this?

**Comment by MoonshineSG** [comment] 2019-01-09 15:37
In the plugin list

**Comment by PRGeno** [comment] 2019-01-09 16:09
I have to assume you must mean the "Force the use of the --user flag with pip install" under the wrench icon in the "Plugin Manager".  That is the only thing remotely similar to "force login" that I can find anywhere in the OctoPrint settings.  

It was already disabled, and I've never changed it since I originally installed OctoPrint about 2 years ago.

**Comment by bigsubgit** [comment] 2019-01-09 18:13
Bingo!!! Without force login is all ok. But what is the solution? I don't
want to disable force login....

Il giorno mer 9 gen 2019 alle ore 17:17 PRGeno <notifications@github.com>
ha scritto:

**Comment by klaus-schuster** [comment] 2019-01-09 19:24
hmmm.. i can enable, disable the flag + fake edit - nothing helps...

**Comment by AMFkuna** [comment] 2019-01-09 20:34
I can confirm, disabling Force Login plugin solve problem with Loading ......
Thanks Moonshine !!

**Comment by PRGeno** [comment] 2019-01-09 21:43
OK, can someone please point out where exactly this mysterious "force login" option can be found?  It is apparently hiding in my installation.

**Comment by keithellis74** [comment] 2019-01-09 22:00
In settings, select Plugin Manager. There is a plugin called ‘Force logon’.  



Keith Ellis

**Comment by PRGeno** [comment] 2019-01-09 22:13
Thank you Keith, found it.  My system is in the middle of a 20 hour print so it will have to wait to test.  But with all of you having success, I have to assume this temporary work around will work for me as well.

**Comment by MoonshineSG** [comment] 2019-01-10 04:17
> I can confirm, disabling Force Login plugin solve problem with Loading ......
> Thanks Moonshine !!
> If you enable it on your system, you can replicate our issue?

yes, i can now replicate the problem and disabling the plugin "Force Login" allows Nautilus to work. I'll work over the next few days to come with a permanent solution, but meanwhile, disable the plugin.

**Comment by klaus-schuster** [comment] 2019-01-10 16:12
> hmmm.. i can enable, disable the flag + fake edit - nothing helps...

found it - thanks

**Comment by PRGeno** [comment] 2019-01-18 00:00
Is there any update on a permanent fix for this issue?

Thanks

**Comment by MoonshineSG** [comment] 2019-01-18 00:12
Not yet. Working with Octoprint developer to find a solution.

**Comment by MoonshineSG** [comment] 2019-01-18 13:54
plugin and ios app will both require an update (app pending apple approval). the 2 contains a workaround fix and a final fix that will work with the future 1.3.11

**Comment by MoonshineSG** [comment] 2019-01-19 01:49
ios app approved by apple and ready. just make sure your plugin is at 1.24  (not 1.23 -  i made a mistake in the commit)

report here any problems...

**Comment by keithellis74** [comment] 2019-01-19 09:15
Hi, I can’t seem to get 1.24 from Octoprint. It says I already have the latest which is 1.23.

IOS app says I only have version 1.20.

**Comment by MoonshineSG** [comment] 2019-01-19 09:47
Made a small versioning error... new app being reviewed by apple. Sorry

**Comment by MoonshineSG** [comment] 2019-01-20 01:41
Make sure you have iOS app version 2.1.7 and plugin version 1.24 and this issue is solved.

**Closed by MoonshineSG** 2019-01-20 01:41 UTC

**Comment by MoonshineSG** [comment] 2019-01-20 02:07
Thanks everyone for you support and patience.
